metadata:
  name: zoo
spec:
  template:
    metadata:
      labels:
        run: zoo
    spec:
      containers:
      - name: zoo
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo





